api_get_token:
    path: /api/v1/getToken

api_refresh_token:
    path: /api/v1/refreshToken

controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
